fail_fast: False
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast  # Check Python file syntax using the ast module.
    -   id: check-json  # Check JSON file syntax.
    -   id: check-merge-conflict  # Check for merge conflict strings.
    -   id: check-toml  # Check TOML file syntax.
    -   id: check-xml  # Check XML file syntax.
    -   id: check-yaml  # Check YAML file syntax.
    -   id: detect-private-key  # Check for private keys.
    -   id: end-of-file-fixer  # Ensure files end with a newline.
    -   id: trailing-whitespace  # Check for trailing whitespace.
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
    - id: ruff  # Check for Python file linting issues and fix them.
      args: [ --fix ]
    - id: ruff-format  # Format Python files.
-   repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
    -   id: yesqa  # Check if there are any unnecessary 'noqa' comments in the code.
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.8
  hooks:
    - id: uv-lock  # Lock dependencies on changes to the pyproject.toml.
